### ISSUE TITLE
Converted schematic "Block palette size does not match expected size" in WorldEdit

### ISSUE THREAD

**Issue by Hi-ImKyle** [GoldenDelicios/Lite2Edit#12]
Seemed to convert just fine
`java -jar .\Lite2Edit.jar --convert .\pfp.litematic`
Then moved the `pfp.schem` to `config/worldedit/schematics` folder (Using WorldEdit on Fabric)
Ran `/schem load pfp.schem` and I get the following
```
[22:42:32] [WorldEdit Task Executor - 5/ERROR]: Uncaught exception occurred in task: Loading schematic pfp
java.io.IOException: Block palette size does not match expected size.
	at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV1Reader.readVersion1(SpongeSchematicV1Reader.java:117) ~[worldedit-mod-7.3.4.jar:?]
	at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV2Reader.doRead(SpongeSchematicV2Reader.java:75) ~[worldedit-mod-7.3.4.jar:?]
	at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV2Reader.read(SpongeSchematicV2Reader.java:63) ~[worldedit-mod-7.3.4.jar:?]
	at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:356) ~[worldedit-mod-7.3.4.jar:?]
	at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:338) ~[worldedit-mod-7.3.4.jar:?]
	at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[worldedit-mod-7.3.4.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75) ~[guava-32.1.2-jre.jar:?]
	at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-32.1.2-jre.jar:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
	at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
[22:42:32] [Render thread/INFO]: [CHAT] Failed to load schematic: Unknown error. Please see console.
```

[Here is the link to the litematic file before conversion](https://drive.google.com/file/d/1r7IKaDSFmKzOug8Md6l6OvxFmM7Odvzv/view?usp=drive_link)

That schem to schematic site doesn't work for me. Nothing happens when I select the schem file, there is an error in the console so I'm assuming it's out of date.

Perhaps WorldEdit has changed? It says it supports schem formats. Only other thing I can think of is Lite2Edit having a bug somewhere.

**Comment by handsome-steve** [comment]
Yeh i had a similar issue, its the converter not doing things right :/

**Comment by GoldenDelicios** [comment]
Hey there, could you set the litematic file on Google Drive to be publicly visible so I can take a look?

**Comment by Hi-ImKyle** [comment]
> Hey there, could you set the litematic file on Google Drive to be publicly visible so I can take a look?

Could've sworn I made it public, mb. Done

**Comment by evanwporter** [comment]
1.2 is glitched. 1.1 works though.

**Comment by GoldenDelicios** [comment]
Thanks for your report and I apologize for the delay. There's an issue with the block palette where cobblestone has 2 numeric ids, and this messes up the conversion. I'm guessing whatever program generated this file has a bug that causes this. Do you have any information as to how this litematic file was created?
