### ISSUE TITLE
Uncaught exception occurred in task: Loading schematic Orbital_Strike_4.0-Orbital_Strike_2.5.schem java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.world.block.BlockState.toBaseBlock(org.enginehub.linbus.tree.LinCompoundTag)" because "state" is null in worldedit

### ISSUE THREAD

**Issue by ghost** [GoldenDelicios/Lite2Edit#13]
Uncaught exception occurred in task: Loading schematic Orbital_Strike_4.0-Orbital_Strike_2.5.schem
java.lang.NullPointerException: Cannot invoke "com.sk89q.worldedit.world.block.BlockState.toBaseBlock(org.enginehub.linbus.tree.LinCompoundTag)" because "state" is null
at com.sk89q.worldedit.extent.clipboard.io.sponge.ReaderUtil.initializeClipboardFromBlocks(ReaderUtil.java:177) ~[?:?]
at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV1Reader.readVersion1(SpongeSchematicV1Reader.java:133) ~[?:?]
at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV2Reader.doRead(SpongeSchematicV2Reader.java:75) ~[?:?]
at com.sk89q.worldedit.extent.clipboard.io.sponge.SpongeSchematicV2Reader.read(SpongeSchematicV2Reader.java:63) ~[?:?]
at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:356) ~[?:?]
at com.sk89q.worldedit.command.SchematicCommands$SchematicLoadTask.call(SchematicCommands.java:338) ~[?:?]
at com.sk89q.worldedit.command.util.AsyncCommandBuilder.runTask(AsyncCommandBuilder.java:158) ~[?:?]
at com.google.common.util.concurrent.TrustedListenableFutureTask$TrustedFutureInterruptibleTask.runInterruptibly(TrustedListenableFutureTask.java:131) ~[guava-32.1.2-jre.jar:?]
at com.google.common.util.concurrent.InterruptibleTask.run(InterruptibleTask.java:75) ~[guava-32.1.2-jre.jar:?]
at com.google.common.util.concurrent.TrustedListenableFutureTask.run(TrustedListenableFutureTask.java:82) ~[guava-32.1.2-jre.jar:?]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[?:?]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[?:?]
at java.base/java.lang.Thread.run(Thread.java:1583) [?:?]
Please help?

**Comment by Nimon77** [comment]
Same here on latest version, v1.1.1 work fine

**Comment by anthony1204** [comment]
lol im doing the same

**Comment by Mace68** [comment]
Same error here with 1.2, 1.1.1 seems to work fine.

VorldEdit and Paper versions:
![image](https://github.com/user-attachments/assets/8e6c8cf3-e581-48c9-a59d-36884b2cedc4)

**Comment by GoldenDelicios** [comment]
This should be fixed in 1.2.1 because of some logic I changed incorrectly. I apologize for the delay.
