### ISSUE TITLE
VER: 1.21 (issue: converting schem files older or made under 1.21) 

### ISSUE THREAD

**Issue by DevilishRar** [GoldenDelicios/Lite2Edit#14]
**Issue: Lite2Edit Tool Incompatibility with 1.21 Schematics**

Hello, after updating to Minecraft 1.21, I’ve noticed that Lite2Edit struggles to load schematics created in any versions prior to 1.21. It seems there’s been a format shift in WorldEdit’s schematics in 1.21, which now prevents schematics from previous versions (e.g., 1.20.4 and earlier) from being read properly. When attempting to load these schematics, errors like the following appear:

> **File could not be read or it does not exist: malformed input around byte (value)**

Or sometimes:

> **File could not be read or it does not exist: null**

If there’s a possible workaround or update that could enable Lite2Edit to handle these legacy formats, it would be greatly appreciated! Thank you!

**Comment by GoldenDelicios** [comment]
Hi thanks for your report. Can you confirm whether using 1.2.1 fixes this issue?
If not, can you confirm that my understanding is correct:
1. You converted a .litematic file that was created in a version before 1.21 to .schem
2. WorldEdit cannot read this file in 1.21

Also if you have access to the server console or logs, please paste the full error stack trace for more information.
A copy of the litematic and converted schematic would also be helpful.

**Comment by DevilishRar** [comment]
Converted many files for testing and these are the outputs

```
File could not be read or it does not exist: malformed input around byte 6481
File could not be read or it does not exist: Invalid tag type: 77
```

Although those happened I tried out some normal schematics that are not converted and some ended up working some old some invalid tag some etc but here are the ones that worked for me when I used FAWE 1.21 plugin
(most of these are all .schematic i bet)

``` 
https://www.minecraft-schematics.com/schematic/7432/download/action/?type=schematic
https://www.minecraft-schematics.com/schematic/7555/download/action/?type=schematic
https://www.minecraft-schematics.com/schematic/14872/download/action/?type=schematic
https://www.minecraft-schematics.com/schematic/13404/download/action/?type=schematic
```

But here are some schematics that didn't work (none converted) (these are all schem and maybe a lil of very very old schematic file)

```
https://www.minecraft-schematics.com/schematic/7337/download/action/?type=schematic
(FAWE) File could not be read or it does not exist: No tag under the name 'WEOriginX' exists If you are specifying a format you may not be specifying the correct one Sponge schematic v2 and v3 both use the .schem file extension To allow FAWE to select the format do not specify one If you are using a litematica schematic it is not supported

https://www.minecraft-schematics.com/schematic/18542/download/action/?type=schematic
(FAWE) File could not be read or it does not exist: malformed input around byte 124

https://www.minecraft-schematics.com/schematic/22098/download/action/?type=schematic
(FAWE) File could not be read or it does not exist: malformed input around byte 10

https://www.minecraft-schematics.com/schematic/19260/download/action/?type=schematic
(FAWE) File could not be read or it does not exist: malformed input around byte 74

https://www.minecraft-schematics.com/schematic/19300/download/action/?type=schematic
(FAWE) File could not be read or it does not exist: malformed input around byte 76
```

Most of the ones that are not working are `.schem` files and the ones working for some reason are the old format `.schematic` idk how and why what I'm thinking is that I think `.schem` formats are broken for some reason and `.schematic` files are fine but the very very old schematics won't work

# **Very Important Note**

I even tested out new 1.21 schematics and schems they also had issues 100% of the schems had issues but schematics some work some don't I think the very very very old schematics don't work while but a little bit newer like the ones I linked the ones of working would work because they aren't very old schematics files just schem files I think are broken in the new 1.21 format maybe I'm not sure but that's what I think how far

---

Btw the same results for the `.schem` also happen to the converted litematica schems

**Additional Findings**

- The converted litematica schems exhibit the same issues as the `.schem` files tested earlier
- This suggests that the problem is consistent across different types of `.schem` files, whether they are original or converted from litematica
- It seems that using `.schematic` files, especially those that are not extremely old, yields better results with FAWE 1.21
- Further investigation might be needed to determine why `.schem` files are not functioning correctly in the new format

also here is the server logs u asked for when loading all of these files. (only the schematics that arent working)
------
```
[15:09:56 INFO]: DevilishRak issued server command: //schematic load schematic url:c5e212b0-22c4-4258-9853-3a1d0cb4caf7
[15:09:56 ERROR]: Error loading a schematic
java.util.NoSuchElementException: No tag under the name 'WEOriginX' exists
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/org.enginehub.linbus.tree.LinCompoundTag.getTag(LinCompoundTag.java:364) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.MCEditSchematicReader.read(MCEditSchematicReader.java:129) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:74) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.hold(ClipboardFormat.java:153) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:436) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$load(SchematicCommandsRegistration.java:331) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[15:10:27 INFO]: DevilishRak issued server command: //schematic load schem url:ba2958af-2b67-44f7-bae4-08df4292baab
[15:10:28 WARN]: Failed to load a saved clipboard
java.io.UTFDataFormatException: malformed input around byte 124
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:641) ~[?:?]
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReaderV3.read(FastSchematicReaderV3.java:132) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.hold(ClipboardFormat.java:153) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:436) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$load(SchematicCommandsRegistration.java:331) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[15:10:46 INFO]: DevilishRak issued server command: //schematic load schem url:2d7155bb-c71d-499f-ae4a-f3b3b33c8bbf
[15:10:47 WARN]: Failed to load a saved clipboard
java.io.UTFDataFormatException: malformed input around byte 10
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:641) ~[?:?]
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReaderV3.read(FastSchematicReaderV3.java:132) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.hold(ClipboardFormat.java:153) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:436) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$load(SchematicCommandsRegistration.java:331) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[15:11:08 INFO]: DevilishRak issued server command: //schematic load schem url:fe218336-b21d-40ab-a898-e13c2728a3f6
[15:11:09 WARN]: Failed to load a saved clipboard
java.io.UTFDataFormatException: malformed input around byte 74
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:641) ~[?:?]
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReaderV3.read(FastSchematicReaderV3.java:132) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.hold(ClipboardFormat.java:153) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:436) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$load(SchematicCommandsRegistration.java:331) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
[15:11:32 INFO]: DevilishRak issued server command: //schematic load schem url:fe1e17f9-2b1c-40eb-96d1-f69deb6efde7
[15:11:33 WARN]: Failed to load a saved clipboard
java.io.UTFDataFormatException: malformed input around byte 76
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:619) ~[?:?]
	at java.base/java.io.DataInputStream.readUTF(DataInputStream.java:550) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.extent.clipboard.io.FastSchematicReaderV3.read(FastSchematicReaderV3.java:132) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardReader.read(ClipboardReader.java:62) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extent.clipboard.io.ClipboardFormat.hold(ClipboardFormat.java:153) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommands.load(SchematicCommands.java:436) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.command.SchematicCommandsRegistration.cmd$load(SchematicCommandsRegistration.java:331) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/org.enginehub.piston.CommandManager.execute(CommandManager.java:157) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommandOnCurrentThread$16(PlatformCommandManager.java:727) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandTask(PlatformCommandManager.java:748) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.handleCommandOnCurrentThread(PlatformCommandManager.java:729) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.PlatformCommandManager.lambda$handleCommand$14(PlatformCommandManager.java:700) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.sk89q.worldedit.extension.platform.AbstractPlayerActor.lambda$runAction$1(AbstractPlayerActor.java:672) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$run$0(AsyncNotifyKeyedQueue.java:48) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.AsyncNotifyKeyedQueue.lambda$call$1(AsyncNotifyKeyedQueue.java:58) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317) ~[?:?]
	at FastAsyncWorldEdit-Bukkit-2.11.2.jar/com.fastasyncworldedit.core.util.task.KeyQueuedExecutorService$KeyRunner.lambda$run$0(KeyQueuedExecutorService.java:150) ~[FastAsyncWorldEdit-Bukkit-2.11.2.jar:?]
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1423) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1312) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1843) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1808) ~[?:?]
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:188) ~[?:?]
```
------------

**Comment by GoldenDelicios** [comment]
I believe this might be the issue at hand: https://github.com/IntellectualSites/FastAsyncWorldEdit/issues/2892
See if updating FAWE to version 2.11.2 helps
