### ISSUE TITLE
getting error message when i try to convert a litematic file to .schem file

### ISSUE THREAD

**Issue by pat-gc** [GoldenDelicios/Lite2Edit#4]
i get this error log when i try to convert the file i dont know why, i folowed the instructions and no other program was using it

please help thanks

this is the error i get : 

java.lang.ArrayIndexOutOfBoundsException: Index 9261 out of bounds for length 9261
	at goldendelicios.lite2edit.Converter.litematicToWorldEdit(Converter.java:67)
	at goldendelicios.lite2edit.Lite2Edit.lambda$0(Lite2Edit.java:69)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.plaf.basic.BasicButtonListener.mouseReleased(BasicButtonListener.java:279)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6635)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6400)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5011)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2772)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4843)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

**Comment by GoldenDelicios** [comment]
Hey there, could you provide the original .litematic file so I can investigate further?

**Comment by pat-gc** [comment]
sure lemme try and find it i tried with other litematic files i really dont get why that one didnt work i had to change some stuff i dont know what i changed for context im making an assembler for  a cpu i made in minecraft so i changed something in the code later without realising what was the issue its weird
so i wasnt able to find the original file since i thoguht it was garbage and put in the trash and emptied it but i have another one that has the same eroor exept diferent numbers: Error while converting 6thmctest.litematic:
java.lang.ArrayIndexOutOfBoundsException: Index 11760 out of bounds for length 11760
[errors.log](https://github.com/GoldenDelicios/Lite2Edit/files/9611356/errors.log)
i made it a zip file cuz github didnt let me put in a .litematic
[6thmctest.zip](https://github.com/GoldenDelicios/Lite2Edit/files/9611360/6thmctest.zip)
and yes it did work with litematica mod
-thanks

**Comment by GoldenDelicios** [comment]
Thank you for your report. I've fixed the issue. Check out version 1.1.1.

**Comment by pat-gc** [comment]
thanks
